SELECT CONCAT('google','.com') AS ConcatFunction

SELECT ASCII(ProductID) NumberCodeOfID
FROM Products

SELECT ASCII('0')

SELECT CHAR(64) AS CodeToCharacter

SELECT LOWER('SQL Functions')

SELECT UPPER('SQL Functions')

SELECT REPLACE('TUTORIAL', 'T', 't')

SELECT GETDATE() 

SELECT DAY('2024-03-04') AS DAY

SELECT MONTH('2024-03-04') AS MONTH

SELECT YEAR('2024-03-04') AS YEAR